# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3
mod_version=1.0.2-dev
maven_group=kiwi.allantaylor
archives_base_name=MarkedGoats
fabric_version=0.154.2+26.2
# wthit_version=19.0.1
# badpackets_version=0.12.2
